import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ReactQueryClientProvider } from '@/lib/reactQuery'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Accmovil | Area de trabajo',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="es" suppressHydrationWarning>
        <body className={inter.className}>{children}</body>
      </html>
    </ReactQueryClientProvider>
  )
}
